server.port: 8090

spring:
  config.import: configserver:http://localhost:8888
  application.name: users-service
  security.oauth2.client.registration:
    google:
      clientId: 142523564407-37u9vflccclbfguvhnpka2jfdmpln43r.apps.googleusercontent.com
      clientSecret: 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
